title: MCR100
description: Academic profile and research projects
url: https://mcr100.github.io
baseurl: ""

markdown: kramdown

plugins:
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      layout: default